<script src="prototype.js" type="text/javascript"></script>
<script src="effects.js" type="text/javascript"></script>
<script src="newsticker.js" type="text/javascript"></script>
<link href="newsticker.css" type="text/css" rel="stylesheet" />
<style type="text/css">
.arrowlistmenu{width: 180px; margin-left:15px;margin-top:14px;padding:0px;}

.arrowlistmenu .menuheader{ /*CSS class for menu headers in general (expanding or not!)*/font: normal 11px Tahoma;color: #000000;background-image:url(images/accordian_menu_item_bg.jpg);background-repeat:repeat-y;border-top:1px solid #e0dfdf;/*border-bottom:1px solid #e0dfdf;*/width:185px;height:25px;line-height:25px;text-indent:10px;margin:0px;padding:0px;cursor:pointer;}.arrowlistmenu .openheader{ /*CSS class to apply to expandable header when it's expanded*/background-image:url(images/accordian_menu_item_bg.jpg);background-repeat:repeat-y;border-top:1px solid #e0dfdf;/*border-bottom:1px solid #e0dfdf;*/width:185px;}.arrowlistmenu ul{ /*CSS for UL of each sub menu*/list-style-type: none;margin: 0;padding: 0;/*background-image:url(ul_bg.gif);width:185px;background-repeat:repeat-y;*/}.arrowlistmenu ul li{font: normal 11px Tahoma;color: #000000;margin:0px;}.arrowlistmenu ul li a{color: #000000;padding-left: 25px; /*link text is indented 19px*/text-decoration: none;font-family:Tahoma;font-size: 11px;}/*.arrowlistmenu ul li a:visited{color: #A70303;}*/.arrowlistmenu ul li a:hover{ /*hover state CSS*/color: #e1261d;}#dhtmlgoodies_slideshow{		width:438px;	/* Total width of slideshow */}			#galleryContainer{		width:438px;		/* Height of the images + 2 */		position:relative;		overflow:hidden;		margin-top:16px;		height:81px;					}	#arrow_left{	position:absolute;	z-index:10;	background-color: #FFF;	left:0px;	height:49px;	padding-top:23px;	padding-right:10px;	width:10px;	}	#arrow_right{	position:absolute;	right:0px;	z-index:10;	background-color: #FFF;		padding:1px;		height:49px;	padding-top:23px;	padding-left:10px;	width:10px;		}	*html #arrow_left{	position:absolute;	z-index:10;	background-color: #FFF;	left:0px;	height:49px;	padding-top:23px;	padding-right:10px;	width:10px;	}		*html #arrow_right{	position:absolute;	right:0px;	z-index:10;	background-color: #FFF;		padding:1px;		height:49px;	padding-top:21px;	padding-left:10px;	width:10px;	}		#theImages{	position:absolute;	height:73px;		width:100000px;	}	#theImages #slideEnd{		float:left;	}	#theImages img{		float:left;		padding:1px;		padding-left:30px;		padding-right:35px;		background-image:url(images/bar.jpg);		height:70px;		background-repeat:no-repeat;		background-position:right;		cursor:pointer;		border:0px;	}	#waitMessage{		display:none;		position:absolute;		left:200px;		top:150px;		background-color:#FFF;		border:3px double #000;		padding:4px;		color:#555;		font-size:0.9em;		font-family:arial;		}		#theImages .imageCaption{		display:none;	}</style>

<script src="Scripts/AC_RunActiveContent.js" type="text/javascript"></script>
