<?php

	require("header.php");
?>
	<h1>About the Performance Engineering Laboratory</h1>
<p>
The Performance Engineering Laboratory (PEL) is concerned with any system where performance issues arise and where the application of theoretical analysis can support the understanding or the design of the system. Results from Queueing Theory are often applied, including statistical formulations, priority schemes, dynamic systems, parallel processing and discrete event modelling and simulation.
</p>
<p>
The aim of PEL is to provide models, tools and analysis to aid in system design, performance, prototyping, testing and evaluation. The types of systems studied include multimedia networks, complex computer systems, data networks, new high-speed Local Area Networks and large software systems.
</p>
<p>
The scope of PEL is currently in Multimedia Networking & Mobile Systems and Distributed Internet-enabled Systems. PEL is located within two Dublin based Universities, Dublin City University (DCU) and University College Dublin (UCD), and within PEL there are a number of labs, namely the Mobile Systems Lab, the Distributed Systems Lab, the Multimedia Networking Lab.
</p>
<p>
PEL at DCU is a research laboratory consisting of approximately 30 staff (academics, postdocs, postgrads, consultants, etc.)
</p>
<p>
There are several hundred publications generated by the lab and this wiki is a database application of these publications. 
</p>
	
<?php
	require("footer.php");
?>